nats-io/nats-architecture-and-design

README.md, adr/ADR-22.md
From base implementation at  https://github.com/nats-io/nats.go/pull/930
Signed-off-by: Waldemar Quevedo <wally@synadia.com>
=> Add notes on implementation of js.Publish retries

adr/ADR-4.md
There were some dangling references that made it less clear that NATS Headers (apart from HTTP Headers) are case-preserving and leave the opinionation of case-sensitivity up to the application implementer.
=> Updates to ADR-4 to clarify NATS Headers are case-preserving

adr/ADR-8.md
Adds `Bytes()` to the bucket Status interface (see https://github.com/nats-io/nats.go/pull/1092)
=> Update ADR 8 KV Status interface

adr/ADR-17.md
Ordered  Consumers should be recreated when heartbeats are missed.
This behaviour was not implemented in all clients and should be, especially after switching ordered consumers to memory storage and R1 which makes them much easier to loose.
This was found out in Go client in https://github.com/nats-io/nats.go/issues/1094
=> Add note about recreating ordered consumer

adr/ADR-32.md
This adds type hints in line with those used by JetStream API to micro responses.
The goal is to be able to attach JSON schema (and others) to these for validation, documentation, discovery of design and more.
These schemas will be surfaced in "nats schema" command as well.
=> add response type hints to micro responses

adr/ADR-32.md
This PR contains changes to how Service API handles schema definitions. 
Instead of one global `Schema` on `Config`, now there are:
- A service-scoped API specification url (passed in config)
- Endpoint-scoped schemas defined when adding each endpoint
=> Update Service API service and endpoint schema definitions

adr/ADR-32.md
Add information on the name of base endpoint - if base endpoint subject is provided by the user, its name should be set to "default" by client libraries.
=> Service API base endpoint name

README.md, adr/ADR-34.md
| Metadata | Value                     |
|----------|---------------------------|
| Date     | 2023-01-18                |
| Author   | @Jarema                   |
| Status   | Approved                  |
| Tags     | jetstream, client, server |
Initially, JetStream Consumers could have only one Filter Subject.
As the number of feature requests to specify multiple subjects increased, this feature was added.
That could also reduce the number of Consumers in general.
Server PR: https://github.com/nats-io/nats-server/pull/3500
To implement the feature without any breaking changes, a new field should be added to Consumer config, both on the server and the clients.
1. The new field is:  
`FilterSubjects []string json:"filter_subjects"`  
2. Subjects can't overlap each other and have to fit the …
=> Add Consumers with Multiple Filters ADR-34

adr/ADR-37.md
Explain the relationship between pull termination and returning from the call e.g. fetch()
=> ADR-37 pull termination clarification

adr-template.md
Some time ago we agreed to add revisions to ADR. Adding it to the template.
=> Add revision table to template

adr/ADR-32.md
This change enables new patterns to be used with `Service API`, like `hedged requests`.
=> Make service queue groups customizable

adr/ADR-32.md
The semver regex was menitioned in standard fields schema info, but not in service configuration.
Added it to config for consistency.
=> Add schema validation to version field

.readme.templ, README.md
After feedback that the journal approach of the typical ADR system is not a good format for aiding development of clients we are refocussing this repository around specifications and larger, living, documents.
We will remain flexible in what goes in here - being useful is what matters, the journal style did not work.
Future PRs might update old ADRs and combine them into later ones marking the old ones as such.
=> Refocus ADR repo around specifications

README.md, adr/ADR-20.md
This commit also cleans up formatting of the spec.
=> Add compression to object store

adr/ADR-37.md
Adds info about update API for consumers in simplification, but without whole API spec, as this is not part of this ADR.
It, however, should be, to become a spec.
API spec will be added in separate PR.
=> Add update consumer to simplification ADR

adr/ADR-8.md
=> Add KV management to KV adr

adr/ADR-8.md
=> Add keys with filters

adr/ADR-37.md
Signed-off-by: Piotr Piotrowski <piotr@synadia.com>
=> Update server reconnect behavior during `consume()`

adr/ADR-8.md
Removed notes on duplicate window. No need to even write duplicate window on kv config since
1. The server will figure it out
2. The user could change it from the cli anyway
This suggestion is made given the behavior of server code (stream.go)...
- If duplicate_window is supplied in the configuration while creating a stream, the server will return an error if it is smaller than the max_age
- If duplicate_window is not supplied, the server will automatically set duplicate window to the smaller of 2 minutes or max_age
Clients can remove sending duplicate_window to the server when creating a KV bucket or can validate that the behavior is correct like here: https://github.com/nats-io/nats.go/blob/98430acd80423b776149f29d625d158f490ac3c5/jetstream/kv.go#L334-L342
=> [Update] ADR-8 Duplicate Window

adr/ADR-40.md
TLS handshake supported server version - Looked like it would only be supported for teh upcoming 2.11. But going back 2.10 releasese its obvious the meant to say 2.10.11
=> TLS handshake supported server version

adr/ADR-32.md
Also formally ensure service metadata is immutable.
=> ADR-32: Adds a way to make queuegroup-less endpoints

adr/ADR-44.md
Update ADR-44 to "Partially Implemented" status.
- Rename "feature level" to "API level" to be consistent with the implementation
- Add missing metadata field `_nats.created.server.api_level` 
- Add section about "When to increment API Level"
=> ADR-44: Update to Partially Implemented

adr/ADR-10.md, adr/ADR-2.md, adr/ADR-28.md, adr/ADR-32.md, adr/ADR-41.md, adr/ADR-8.md
Links to other ADR documents were normalized based off of relative directories which GitHub supports:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#relative-links-and-image-paths-in-readme-files
=> Normalize links to other ADR documents

.gitignore, adr/ADR-8.md
Clearly mark non direct get based gets as deprecated
=> Expand KV ADR for Per Msg TTLs

adr/ADR-31.md
This adds missing multi_last configuration to request payload (with examples)
Signed-off-by: Piotr Piotrowski <piotr@synadia.com>
=> Update direct get request payload in ADR-31

adr/ADR-8.md
=> Add metadata to kv, remove read-after-write guarantee

adr/ADR-50.md
Update wording around restrictions for how `Nats-Expected-Last-Sequence`, `Nats-Expected-Last-Msg-Id`, and `Nats-Expected-Last-Subject-Sequence` are handled.
Relates to https://github.com/nats-io/nats-server/pull/7060
=> ADR-50: Update expected check specifics

README.md, adr/ADR-35.md
Although mostly done and anticipated to land in 2.10, this ADR describes the filestore compression and the configuration surface area required for clients.
=> ADR-35: JetStream Filestore Compression

adr/ADR-42.md
This adds the ability for overflow clients to take over the consumer when no unlimited clients are active.
Without this ability the consumer could stall until the limits are reached and once reached again stall once the thresholds fall below the stated limits resulting in unconsumed messages.
Essentially the current design works as long as all regions have actively consuming clients, this adds a feature that allows regions to create a cascading HA setup between them where for example us-east could take over for us-west after 5 seconds and eu-west would only step in after 10 seconds
=> ADR-42 support failover on overflow policy as well as priority client policy

adr/ADR-40.md
=> Add client statistics to the connection spec

adr/ADR-50.md
Signed-off-by: Piotr Piotrowski [piotr@synadia.com](mailto:piotr@synadia.com)
=> ADR-50: Remove unsupported header mention
