nats-io/nats-architecture-and-design

- README.md
- adr-template.md
- adr/ADR-1.md
- adr/ADR-10.md
- adr/ADR-2.md
- adr/ADR-3.md
- adr/ADR-4.md
- adr/ADR-5.md
- adr/ADR-6.md
- adr/ADR-7.md
- adr/ADR-8.md
- adr/ADR-9.md
- main.go
Also avoid some redundant info in the metadata section
> add the ADR-8 - key value stores

- README.md
- adr/ADR-8.md
> remove old style header left over from transfer

- .github/ISSUE_TEMPLATE/feature_documentation.md
> issue template for documentation

- .github/ISSUE_TEMPLATE/client_enhancement.md
> [modify] Update client_enhancement.md template

- adr/ADR-1.md
> [modifying] ADR-1:  update jetstream api adr for reality

- .github/ISSUE_TEMPLATE/feature_documentation.md
- README.md
- adr-template.md
- adr/ADR-12.md
- main.go
> [adding] ADR-12: JetStream encryption at rest

- adr/ADR-7.md
> Update errors ADR for improve functions

- adr/ADR-15.md
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>
> [UPDATED] Clarify check of $JS.ACK token count by the libraries

- .github/ISSUE_TEMPLATE/client_enhancement.md
> update rust ownership in new issues

- adr/ADR-8.md
This updates the ADR for recent discussions and states
clearly that this is now a stable point.
A rough roadmap is included
> [update] ADR-8 prepare for stable 1.0 version KV

- README.md
- adr/ADR-21.md
> [adding] ADR-21 NATS Configuration Contexts

- README.md
- adr/ADR-30.md
Provide architectural coverage of a server implementation that is integral to several user-level features in the server.
> ADR-30 Subject Transform

- README.md
- adr/ADR-28.md
As-built ADR for the JetStream RePublish feature. Ready to merge.
> ADR-28 RePublish

- README.md
- adr/ADR-31.md
This is an implementation ADR for the Direct Get and Subject-Appended Direct Get features.
> ADR-31 Direct Get

- .github/ISSUE_TEMPLATE/client_enhancement.md
In addition, remove Ivan and Matthias from the assignee list.
Signed-off-by: Byron Ruth <b@devel.io>
> Change notification for docs owner

- adr/ADR-10.md
See nats-io/nats-architecture-and-design#4
> [adr-10] Change status to Implemented

- adr/ADR-32.md
> ensure time is in the same tz for global deployments

- adr/ADR-32.md
change apiUrl to api_url for field name consistency
> change apiUrl field name

- adr/ADR-32.md
* Changes to defaults are based on conversations with @aricart 
* Captured handling 404's against pending counts
* Suggested warnings to be telegraphed to user.
> Adding detail PR 176 js simplification ADR

- adr/ADR-20.md
As agreed, it's the only change for now to Object Store.
It aligns with other APIs leveraging the metadata pattern, adding it to Bucket and Object.
> Add metadata to object store

- adr/ADR-30.md
Update to reflect the new changes from https://github.com/nats-io/nats-server/pull/4152
> Update ADR with changes concerning using all of the wildcard tokens in the transform

- adr/ADR-40.md
> Add on-demand reconnect to Connect Spec

- .github/ISSUE_TEMPLATE/client_enhancement.md
> Remove Casper from issue assignees

- .github/ISSUE_TEMPLATE/client_enhancement.md
As @caspervonb is now handling the Python client, this PR updates the templates so he gets the notifications.
> Add Casper to template

- adr/ADR-8.md
Fine tuning KV Management section.
> [EDIT] Key Value ADR 8

- .github/workflows/validate.yaml
- README.md
- adr-template.md
- adr/ADR-15.md
- go.mod
- go.sum
- main.go
> Adds a deprecated status

- adr/ADR-42.md
This commit also fixes the formatting of the document.
> Add clients implementation for Priority Groups

- adr/ADR-20.md
> Remove experimental mention from Object Store

- adr/ADR-37.md
This a a grammar review before making modifications to status message handling.
> [EDIT] ADR-37 Grammar review

- adr/ADR-49.md
Changes as made in nats-io/nats-server#6988.
Signed-off-by: Neil Twigg <neil@nats.io>
> ADR-49: Updates for sourcing-aware counters

- README.md
- adr/ADR-44.md
Remove the concerns section as with the addition of required API header and offline assets address this completely
> ADR-44: Mark as implemented

- adr/ADR-49.md
Signed-off-by: Piotr Piotrowski [piotr@synadia.com](mailto:piotr@synadia.com)
> ADR-49: Update client implementation details

- adr/ADR-50.md
2.12.0 released atomic batch publish, but didn't contain deduplication support yet. Now that we've decided to have both atomic batch publishing (atomic & consistent) and non-atomic high-speed publishing (performance), we can make a decision around how deduplication works as well.
When the `Nats-Msg-Id` deduplication header is used and a duplicate message is detected, the whole batch gets rejected with an error: `atomic publish batch contains duplicate message id`. This ensures the all-or-nothing-gets-persisted atomic nature is preserved, also when deduplication is used. There are no exceptions.
The high-speed non-atomic batching could then support deduplication differently by allowing them to be omitted from the stored messages, similar to how `js.PublishAsync` would work.
> ADR-50: Support atomic deduplication
